services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend-dist:/usr/share/frontend-dist
    networks:
      - video-network

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file:
      - ./api/.env

    container_name: video-api

    environment:
      PORT: 8080

      RABBITMQ_URL: amqp://admin:admin123@rabbitmq:5672

      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: videos

      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: video_platform
      DB_USER: video_user
      DB_PASSWORD: video_password
    expose:
      - "8080"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - video-network

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: video_platform
      MYSQL_USER: video_user
      MYSQL_PASSWORD: video_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "video_user",
          "-pvideo_password",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - video-network

  #15672 -> GUI console
  rabbitmq:
    image: rabbitmq:4-management
    container_name: video-rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - video-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - frontend-dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - api
    networks:
      - video-network

  # 9000 → Object storage API
  # 9001 → Web administration console
  minio:
    image: minio/minio
    container_name: video-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - video-network

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile

    container_name: video-worker

    command: node dist/worker.js

    environment:
      RABBITMQ_URL: amqp://admin:admin123@rabbitmq:5672

      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: video_platform
      DB_USER: video_user
      DB_PASSWORD: video_password

      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: videos

    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started

    networks:
      - video-network

  redis:
    image: redis:7-alpine
    container_name: video-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - video-network

networks:
  video-network:
    driver: bridge

volumes:
  mysql_data:
  minio-data:
  frontend-dist:
